# Generated by Django 5.1.6 on 2025-02-25 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('workout_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('total_elapsed_time', models.FloatField()),
                ('total_timer_time', models.FloatField()),
                ('enhanced_avg_speed', models.FloatField(blank=True, null=True)),
                ('avg_speed', models.FloatField(blank=True, null=True)),
                ('enhanced_max_speed', models.FloatField(blank=True, null=True)),
                ('max_speed', models.FloatField(blank=True, null=True)),
                ('total_distance', models.FloatField()),
                ('min_heart_rate', models.IntegerField(blank=True, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('max_heart_rate', models.IntegerField(blank=True, null=True)),
                ('total_calories', models.IntegerField()),
                ('total_ascent', models.FloatField()),
                ('total_descent', models.FloatField()),
                ('sport', models.CharField(max_length=100)),
                ('sub_sport', models.CharField(max_length=100)),
                ('num_laps', models.IntegerField(blank=True, null=True)),
                ('threshold_power', models.IntegerField(blank=True, null=True)),
                ('auto_lap_duration', models.FloatField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.workout')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('position_lat', models.FloatField(blank=True, null=True)),
                ('position_long', models.FloatField(blank=True, null=True)),
                ('gps_accuracy', models.IntegerField(blank=True, null=True)),
                ('enhanced_altitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('enhanced_speed', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('battery_soc', models.FloatField(blank=True, null=True)),
                ('ascent', models.FloatField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='workouts.workout')),
            ],
        ),
        migrations.CreateModel(
            name='PowerZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_index', models.IntegerField()),
                ('high_value', models.IntegerField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_zones', to='workouts.workout')),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('total_elapsed_time', models.FloatField()),
                ('total_timer_time', models.FloatField()),
                ('avg_speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('total_distance', models.FloatField()),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('max_heart_rate', models.IntegerField(blank=True, null=True)),
                ('total_calories', models.IntegerField()),
                ('total_ascent', models.FloatField()),
                ('total_descent', models.FloatField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='workouts.workout')),
            ],
        ),
        migrations.CreateModel(
            name='HRZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_index', models.IntegerField()),
                ('high_bpm', models.IntegerField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_zones', to='workouts.workout')),
            ],
        ),
    ]
