# Generated by Django 5.1.6 on 2025-02-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='file',
            new_name='file_path',
        ),
    ]
